### ISSUE TITLE
Payment stuck

### ISSUE THREAD

**Issue by tx1683** [bitlum/payserver#21]
I was exchanging BTC in Lightning to BTC on chain and something went wrong. I have "Withdraw failed" error. GUI suggested opening live chat with you, but link doesn't work. You also do not provide another support channel, so I am posting here. 
My order ID is 106fc9e0-f933-4d06-bbdf-3a578a6a1461 and destination address was bc1q338hgc98ah7kdlkdlpngmsnsf5u7t9c2nsw2c0

**Comment by denengineer** [comment]
Resolved)
